name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${exp.name}
log: ${exp.dir}/exp.log
mode: visualize
load:
  save_dir: ${load_path}$
  epochs: null
  model_only: true
  strict: ${strict}$
  wait: false
policy:
  pin_memory: false
  lr: ${lr}$
  batch_size: ${batch_size}$
  device: gpu
  n_warmup: ${warmup}$
  check_interval: -2
